
export const types = {
  uiSetError: '[UI] Set Error',
  uiRemoveError: '[UI] Remove Error',
  uiStartLoading: '[UI] Start loading',
  uiFinishLoading: '[UI] Finish loading',
  uiOpenModal:'[ui] Open modal',
  uiCloseModal:'[ui] Close modal',
  
  authChecking:'[auth] Checking login state',
  authCheckingFinish:'[auth] Finish checking login state',
  authStartLogin:'[auth] Start login',
  authLogin:'[auth] Login',
  authStartRegister:'[auth] Start Register',
  authStartTokenRenew:'[auth] Start token renew',
  authLogout:'[auth] Logout',

  eventLoaded:'[event] Events Permissions Loaded',
  eventSetActive:'[event] Set active Permission',
  eventUpdated:'[event] Set update State Permission',
  eventFilter:'[event] Filter Data Permission',
  eventClearActive:'[event] Event clear permission active',
  attendanceCheckingStart:'[attendance] Start cheking state',
  attendanceCheckingFinish:'[attendance] Finish cheking state',
  attendanceUpdate:'[attendance event] Attendance update data',
  attendanceFilter:'[attendance event] Attendance filter data',
  myattendanceFilter:'[attendance event] Attendance User filter',
  attendanceDashboardUpdate:'[attendance event] Attendance data dashboard',
  attendanceUser:'[attendance event] Get Attendance user',
}
